development:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  google_client_id: <%=ENV["437311968162-uj7o36jtkhp0kp7c725vm6e361oh61aj.apps.googleusercontent.com"] %>
  google_client_secret: <%=ENV["b_e0ehnKspIbK-NTWwVh62K5"] %>


test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
